### ISSUE TITLE
Add ability to sort the snippets. 

### ISSUE THREAD

**Issue by logankilpatrick** [30-seconds/30-seconds-web#34] opened 2019-12-26 16:01 UTC
There should be the ability to sort the snippets by different metrics.

**Comment by Chalarangelo** [comment] 2019-12-26 17:07
Duplicate of #23. 

**TL;DR:** We currently order by popularity, soon we will add ordering alphabetically, too, allowing you to switch between orders.

**Closed by Chalarangelo** 2019-12-26 17:07 UTC

**Comment by logankilpatrick** [comment] 2019-12-26 17:17
Would be nice to do by difficulty as well.
