### ISSUE TITLE
Truncated title in snippet page

### ISSUE THREAD

**Issue by Trinityyi** [30-seconds/30-seconds-web#294] opened 2021-01-20 15:01 UTC
![IMG_20210120_165805](https://user-images.githubusercontent.com/13429517/105192558-e6042d00-5b40-11eb-80cf-a9239321c82a.jpg)

**Comment by Chalarangelo** [comment] 2021-02-03 18:17
Closing for the time being as we cannot reproduce this in the current build. Will reopen if there's a regression.

**Closed by Chalarangelo** 2021-02-03 18:17 UTC
Labels: Size: S/2, UI/UX, bug
